---
title: 股票是什么
slug: what-is-stock
img: /images/thumbnail/attachment/20180228/0735171472a94a9c945c83ea524f0fef.jpg
categories: 散文随笔
tags:
  - 股票
  - 母鸡经济学
keywords: '股票,母鸡经济学'
description: 最近看了下股票相关的东西，刚好看到一则比较有意思的说明股票是什么的故事，转载下来！
date: 2018-02-28 15:54:54
updated: 2018-05-29 12:46:25
---

= 股票是什么
:author: belonk.com
:date: 2018-05-29
:description: 股票是什么,用“母鸡经济学”，通过一个通俗的故事来讲解股票是什么
:doctype: article
:email: belonk@126.com
:encoding: UTF-8
:favicon: 
:generateToc: true
:icons: font
:imagesdir: images
:keywords: 股票,母鸡经济学
:linkcss: true
:numbered: true
:stylesheet: 
:tabsize: 4
:tag: 股票,母鸡经济学
:toc: auto
:toc-title: 目录
:toclevels: 4
:website: https://belonk.com

最近看了下股票相关的东西，刚好看到一则比较有意思的说明股票是什么的故事，转载下来！

[blockquote]
____
戈登·盖克曾经是华尔街的一名金融大亨，1987年因为炒股搞内幕交易被抓。2001年戈登出狱后重操旧业，然后碰上了金融风暴……上面说的，是两部《华尔街》电影的剧情。为了让普通观众更好理解故事，编剧借角色之口，打了很多生动形象的比喻。主演迈克尔·道格拉斯还因此拿了个奥斯卡影帝。打比喻，讲故事，是普及金融知识的最佳手段。这也是我们开办“母鸡经济学”专栏的初衷，我们请了一批一线的金融从业者，请他们用这种方式，给大家聊聊金融这点事。本期作者为私募基金公司交易员2.5。
____ 

从前，在一片广阔的大草原上，有很多只母鸡，他们，吃着火锅唱着歌，吃着青草下着蛋。但是，母鸡们又不愿意像这样日复一日的吃草，下蛋。于是，一场革命性的变革即将到来……

== Chapter 1 股票的产生

有一天，一只有远见的花母鸡突然想到，如果我能吃到更多，更好的虫子，岂不是可以进化成母鸡中的战斗机，下更多、更好的蛋？

可是，问题来了，这只花母鸡手里没有钱，就只能卖身。花母鸡找到了一只聪明的猴子，说，你给我钱，我之后每下两个蛋，都能分你一个。

猴子当然聪明得很，他心想：花母鸡每年能生100个蛋，一个蛋能卖1块钱，于是我每年就能分50块钱，那我给你1000块钱吧，这样我20年就能回本。

花母鸡说，OK，我这有50张 **母鸡券**，拿着作为凭证吧。

于是，猴子这50张母鸡券就被称为“ **股份**”，而他所做的1000块钱投资，就叫“按20倍 **市盈率**入股”。啥叫市盈率？就是母鸡券的价格除以每年可以领到的鸡蛋，也可以理解为多久“回本”。这个数字，越低越好。
 
[blockquote]
____
戈登·盖克曾经是华尔街的一名金融大亨，1987年因为炒股搞内幕交易被抓。2001年戈登出狱后重操旧业，然后碰上了金融风暴……上面说的，是两部《华尔街》电影的剧情。为了让普通观众更好理解故事，编剧借角色之口，打了很多生动形象的比喻。主演迈克尔·道格拉斯还因此拿了个奥斯卡影帝。打比喻，讲故事，是普及金融知识的最佳手段。这也是我们开办“母鸡经济学”专栏的初衷，我们请了一批一线的金融从业者，请他们用这种方式，给大家聊聊金融这点事。本期作者为私募基金公司交易员2.5。
____ 

== Chapter 2 股东的权益

花母鸡拿着猴子的钱，开开心心的吃了很多虫子，理所当然的也生了更多的蛋。

第一年，花母鸡下了100个蛋，分了猴子50个，猴子很开心。这，就叫做“ **分红**”。

第二年，花母鸡还是下了100个蛋，但花母鸡把猴子叫过来开了个股东大会，说我用这100个蛋换个大鸡窝，以后每年我都能多生10个蛋，股东你觉得如何呀？猴子一想，我原来每年收益5%，用50个蛋换以后每年5个蛋，每年收益10%，10年回本，合算！这，就叫做 **有效率的再投资**。

这时候，聪明猴投资母鸡的事儿在动物圈传开了，猩猩这时候跑过来说，我给你1000块钱，要不你把50个母鸡券卖给我？

聪明猴心想，我特么又不是傻B，就跟猩猩说：我这个母鸡品种好，叫 **价值鸡**，现在每年生110个蛋，以后还能健康生蛋50年，我按照20年回本卖给你，怎么也得1100！猩猩说，好好好，买买买！

于是，动物圈的第一次股权交易发生了，而单张母鸡券的价格，也就从20元，上浮到了22元。这，就是 **股价上浮**的原因之一。
 
[blockquote]
____
戈登·盖克曾经是华尔街的一名金融大亨，1987年因为炒股搞内幕交易被抓。2001年戈登出狱后重操旧业，然后碰上了金融风暴……上面说的，是两部《华尔街》电影的剧情。为了让普通观众更好理解故事，编剧借角色之口，打了很多生动形象的比喻。主演迈克尔·道格拉斯还因此拿了个奥斯卡影帝。打比喻，讲故事，是普及金融知识的最佳手段。这也是我们开办“母鸡经济学”专栏的初衷，我们请了一批一线的金融从业者，请他们用这种方式，给大家聊聊金融这点事。本期作者为私募基金公司交易员2.5。
____ 

== **Chapter 3 市场形成**

这个交易做成以后，在动物圈引发了轰动，各种动物都蠢蠢欲动，尤其是那些安安稳稳下蛋的母鸡们。于是，每个品种的母鸡，都发行了带有自己印记的母鸡券，给小动物们互相买卖。

**老虎王二**虽然并不知道这些动物在弄啥嘞，那些母鸡券貌似只有“卵”用，但作为大王，底下动物干什么都得管着才行（他们的确啥都不懂），于是他效仿大洋彼岸隔壁森林发达市场的老王颁布了一项规定：母鸡可以在老虎家向所有动物公开拍卖自己的母鸡券，所有的母鸡券都必须在老虎家里交易，这就叫做 **股票交易市场**。

而母鸡必须在老虎家做体检，登记所有信息，方便动物们深入了解母鸡，另一方面动物们也容易找到自己的交易对手，这样 **傻傻的犀牛大象**也毫不费力就可以买卖母鸡券了！
 
[blockquote]
____
戈登·盖克曾经是华尔街的一名金融大亨，1987年因为炒股搞内幕交易被抓。2001年戈登出狱后重操旧业，然后碰上了金融风暴……上面说的，是两部《华尔街》电影的剧情。为了让普通观众更好理解故事，编剧借角色之口，打了很多生动形象的比喻。主演迈克尔·道格拉斯还因此拿了个奥斯卡影帝。打比喻，讲故事，是普及金融知识的最佳手段。这也是我们开办“母鸡经济学”专栏的初衷，我们请了一批一线的金融从业者，请他们用这种方式，给大家聊聊金融这点事。本期作者为私募基金公司交易员2.5。
____ 

== Chapter 4 股价

大家已经可以想到，假设一个母鸡一夜之间变成了胖母鸡，生蛋加倍，那么凭借相应母鸡券就可以领到双倍的鸡蛋，所以母鸡券价格翻倍；反之今夜母鸡得了禽流感，卒，对应母鸡券就一文不值。

那么再许许多多个夜晚，什么都没有发生，还是原来的母鸡，还是生普通的蛋，为什么母鸡券还是涨了跌了？原因很复杂，或许是猴子认为母鸡会变胖，或许是因为猩猩想娶媳妇儿急需用钱，但无论怎样的原因， **母鸡券的价格上涨或下降，母鸡都得不到任何直接的好处或者是坏处，还是原来的母鸡，还是生普通的蛋。**

**而股价，有时候跟母鸡本身，并没有什么关系。**
 
[blockquote]
____
戈登·盖克曾经是华尔街的一名金融大亨，1987年因为炒股搞内幕交易被抓。2001年戈登出狱后重操旧业，然后碰上了金融风暴……上面说的，是两部《华尔街》电影的剧情。为了让普通观众更好理解故事，编剧借角色之口，打了很多生动形象的比喻。主演迈克尔·道格拉斯还因此拿了个奥斯卡影帝。打比喻，讲故事，是普及金融知识的最佳手段。这也是我们开办“母鸡经济学”专栏的初衷，我们请了一批一线的金融从业者，请他们用这种方式，给大家聊聊金融这点事。本期作者为私募基金公司交易员2.5。
____ 

哦对了，开头提到的迈克尔·道格拉斯生活中可不像电影里那样呼风唤雨，他自己炒股赔了据说高达1亿美元。

原文：

- 作者：邹波 链接：https://www.zhihu.com/question/25215182/answer/54368155[]
 
  